a = input('Digite algo: ')
print('O tipo desse valor é ', type(a))
print('Só tem espaços? ',a.isspace)
print('É um número? ',a.isnumeric)
print('É alfabético? ',a.isalpha)
print('É alfanúmérico? ',a.isalnum)
print('Está em maiúsculas?' ,a.isupper)
print('Está em minusculas?', a.islower)
print('Está capitalizada? ', a.istitle)