a = int(input('Digite o número que você quer a tabuada: '))

print('{} x {} = {}'.format(a,1,a*1))
print('{} x {} = {}'.format(a,2,a*2))
print('{} x {} = {}'.format(a,3,a*3))
print('{} x {} = {}'.format(a,4,a*4))
print('{} x {} = {}'.format(a,5,a*5))
print('{} x {} = {}'.format(a,6,a*6))
print('{} x {} = {}'.format(a,7,a*7))
print('{} x {} = {}'.format(a,8,a*8))
print('{} x {} = {}'.format(a,9,a*9))
print('{} x {} = {}'.format(a,10,a*10))